spring:
  application:
    name: UberProject-LocationService
server:
    port: 7777

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
      preferIpAddress: true

